ARG IMAGE=kingces95/sshd
ARG VARIANT=latest
FROM ${IMAGE}:${VARIANT}
LABEL maintainer "Chris King - https://github.com/kingces95"
ARG COMMIT
ARG USER=vscode

# download and extract vscode
USER ${USER}
COPY vscs/get* /tmp/scripts/
WORKDIR /tmp/scripts
RUN ./get-stable.sh ${COMMIT}

# start sshd
USER root
COPY vscs/start* /tmp/scripts/
ENV user=${USER}
ENV commit=${COMMIT}
ENTRYPOINT ./start-as.sh $user $commit && /usr/sbin/sshd -D -e