version: "3.7"

services:
  my-vscs:
    image: kingces95/githubtainer-myvscs

  my-bridge:
    image: kingces95/githubtainer-mybridge
    environment:
      - name=myRelay
      - namespace=myRelayNamespace
      - host=my-vscs
      - port=22
      - portName=ssh
      - policy=myRelayPolicyAll
      - key=nlVQSJbcgZbu/wGRbcZNH0WX95uAKu/EC/6wKL+LrBU=
