#!/usr/bin/env bash
. $(dirname ${BASH_SOURCE})/../dsl.sh

main() {
    local line
    local production
    local production_name
    local identifier
    local name

    while read name line production_name identifier; do
        production=${!production_name}

        if (( production == PRODUCTION_ARG_ALIAS )); then
            echo $name $identifier 
        fi
    done
}

main "$@"