#!/usr/bin/env bash

main() {
        
    local path='.'
    for i in "$@"; do
        path="${path}/${i}"
    done

    (
        cd "$path"
        for entry in *; do 
            [ -d "$entry" ] && [ -x "$entry" ] && echo $entry
        done
    )
}

main "$@"